spring:
  liquibase:
    change-log: classpath:changelog-master.xml
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9081/mem:proddb
    username: admin
    password: admin