management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
hystrix:
  metrics:
    enabled: true        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://travel-management-eureka-server:8761/eureka
s2:
  client:
    id: s2-client
    secret: secret
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: 15
      queueSizeRejectionThreshold: 300
ribbon.ConnectTimeout: 3000
ribbon.ReadTimeout: 3000
    